import { A2AClient } from '@a2a-js/sdk/client';
import { tool } from '@langchain/core/tools';
import type {
  AgentCard,
  AgentSkill,
  Message,
  MessageSendConfiguration,
  MessageSendParams,
  Part,
  PushNotificationConfig,
  Task,
  TaskArtifactUpdateEvent,
  TaskStatusUpdateEvent,
  SendMessageResponse,
  SendMessageSuccessResponse,
} from '@a2a-js/sdk';
import { DynamicStructuredTool } from 'langchain/tools';
import { z } from 'zod';



export async function a2a2langchain(
    options: {
      cardUrl: string
    }
): Promise<DynamicStructuredTool[]> {

  if (!options.cardUrl) {
    throw new Error('Agent card or cardUrl must be provided to initialise the A2A client.');
  }
  const client = await A2AClient.fromCardUrl(options.cardUrl, {});
  const resolvedAgent =  (await client.getAgentCard());
  const tools: DynamicStructuredTool[] = [];
  resolvedAgent.skills.forEach((skill: AgentSkill) => {
    const objTool: any =  tool(
        async (): Promise<any> => {
          console.log('a2a2langchain: sending message to agent', arguments);
          const message: MessageSendParams = {
            //configuration: null,
            message: {
              contextId: "x",
              /**
               * The URIs of extensions that are relevant to this message.
               */
              extensions: ["asdf"],
              /**
               * The type of this object, used as a discriminator. Always 'message' for a Message.
               */
              kind: "message",
              /**
               * A unique identifier for the message, typically a UUID, generated by the sender.
               */
              messageId: "test-messageId",
              /**
               * Optional metadata for extensions. The key is an extension-specific identifier.
               */
              metadata: {},
              /**
               * An array of content parts that form the message body. A message can be
               * composed of multiple parts of different types (e.g., text and files).
               */
              parts: [],
              /**
               * A list of other task IDs that this message references for additional context.
               */
              referenceTaskIds: [],
              /**
               * Identifies the sender of the message. `user` for the client, `agent` for the service.
               */
              role: "agent", // "agent" | "user";
              /**
               * The identifier of the task this message is part of. Can be omitted for the first message of a new task.
               */
              taskId: "test-taskId",
            },
            metadata: { }
          }
          return await client.sendMessage(message);
        },
        {
          name: skill.id,
          description: skill.description,
          schema: z.object({
            a: z.number(),
            b: z.number(),
          }),
        }
    );
    tools.push(objTool);
  })


  return tools;
}
